server:
  port: 8086

spring:
  application:
    name: inops-query
eureka:
  instance:
    hostname: INOPS-QUERY
    prefer-ip-address: true
    ip-address: 192.168.1.71
  client:
    service-url:
      defaultZone: http://192.168.1.71:8761/eureka/


  data:
    mongodb:
      uri: mongodb://admin:password@192.168.1.23:27017/ContractLabour?authSource=admin  # ✅ MongoDB Connection

    kafka:
      bootstrap-servers: http://192.168.1.23:9092
      consumer:
        group-id: query-service
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.value.default.type: "com.inops.query.model.KafkaEvent"
          spring.json.trusted.packages: "*"

camel:
  component:
    kafka:
      brokers: localhost:9092