server:
  port: 8086

spring:
  application:
    name: inops-query
eureka:
  instance:
    hostname: INOPS-QUERY
    prefer-ip-address: true
    ip-address: 192.168.70.176
  client:
    service-url:
      defaultZone: http://192.168.70.176:8761/eureka/




    kafka:
      bootstrap-servers: http://49.206.252.89:9092
      consumer:
        group-id: query-services
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.value.default.type: "com.inops.query.model.KafkaEvent"
          spring.json.trusted.packages: "*"

camel:
  component:
    kafka:
      brokers: localhost:9092


  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    driver:
      reactive:
        change-streams-enabled: true