server:
  port: 8086

spring:
  application:
    name: inops-query
eureka:
  instance:
    hostname: INOPS-QUERY
    prefer-ip-address: true
    ip-address: 192.168.1.11
  client:
    service-url:
      defaultZone: http://192.168.1.11:8761/eureka/

    kafka:
      bootstrap-servers: http://122.166.245.97:9093
      consumer:
        group-id: query-services
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.value.default.type: "com.inops.query.model.KafkaEvent"
          spring.json.trusted.packages: "*"

camel:
  component:
    kafka:
      brokers: localhost:9092


  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    driver:
      reactive:
        change-streams-enabled: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://122.166.245.97:8080/realms/inops
          jwk-set-uri: http://122.166.245.97:8080/realms/inops/protocol/openid-connect/certs

keycloak:
  jwk-set-uri: http://122.166.245.97:8080/realms/inops/protocol/openid-connect/certs

kafka:
  url: http://122.166.245.97:9093
db:
  host: 122.166.245.97:27017
logstash:
  host: 122.166.245.97