server:
  port: 8082

spring:
  application:
    name: inops-query
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 192.168.1.71
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/